### ISSUE TITLE
clang-tidy runs that produce warnings are cached

### ISSUE THREAD

**Issue by erijo** [matus-chochlik/ctcache#15]
It seems like ctcache caches runs that have produced clang-tidy warnings, so that the next time the same file is processed no warning is shown.

Take this file (warning.cpp):
```cpp
#include <string>
#include <vector>

void Foo(const std::vector<std::string> bar)
{
}

void Bar()
{
  std::vector<std::string> foo{"foo", "bar"};
  Foo(foo);
}
```

When run with ctcache:
```
% ./clang-tidy-cache clang-tidy --checks=performance-\* warning.cpp -- g++ -c warning.cpp -o warning.o
8 warnings generated.
warning.cpp:4:41: warning: the const qualified parameter 'bar' is copied for each invocation; consider making it a reference [performance-unnecessary-value-param]
void Foo(const std::vector<std::string> bar)
                                        ^
                                       &
Suppressed 7 warnings (7 in non-user code).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
% ./clang-tidy-cache clang-tidy --checks=performance-\* warning.cpp -- g++ -c warning.cpp -o warning.o
<no output>
```

One option would be to not cache runs that have produced output on stdout.

**Comment by matus-chochlik** [comment]
Hi, please check the latest `main`

**Comment by erijo** [comment]
There are a few problems with that change:

1. The exit code from clang-tidy-cache is 1, but the exit code from clang-tidy is 0. In this case I want exit code 0 as I want the warning(s) but don't want the build to stop because of this. So it's important that clang-tidy-cache has the same exit code as clang-tidy.
2. The warning, which is printed to stdout and not stderr, is suppressed and isn't shown any more.
3. If I fix the warning from clang-tidy (by adding & before bar) I still get an error from clang-tidy-cache (and a cache miss) due to the "Suppressed 7 warnings..." text that clang-tidy logs to stderr.

**Comment by matus-chochlik** [comment]
Please try the next one

**Comment by erijo** [comment]
Yes, that looks much better. Thanks!

(You could perhaps skip the capture of stderr and just pass that through, but that's a minor detail.)

**Comment by matus-chochlik** [comment]
I'll leave it as it is for now, there shouldn't be too much data passing through stderr.

**Comment by erijo** [comment]
Ok! I'm happy with the fix so closing this.
