### ISSUE TITLE
run-clang-tidy support

### ISSUE THREAD

**Issue by jeremy-coulon** [matus-chochlik/ctcache#16]
`run-clang-tidy` is a tool that reads a compilation DB and invokes `clang-tidy` for each source file in parallel and then aggregates the results into a single file:

https://github.com/llvm/llvm-project/blob/main/clang-tools-extra/clang-tidy/tool/run-clang-tidy.py

I tried to use `ctcache` and `run-clang-tidy` together.

You can run this setup in a directory containing the compilation DB with:
`run-clang-tidy -export-fixes clang-tidy.yaml -clang-tidy-binary clang-tidy`
where `clang-tidy` executable found in `$PATH` is a ctcache wrapper.

`run-clang-tidy` invokes, for each source file, a command that looks like the following:
`clang-tidy -export-fixes /tmp/tmppri1nz_t/tmpeko_clr7.yaml -p=/absolute/path/to/CWD /path/to/file.cpp`

This causes 2 issues with ctcache:
1. path to compilation DB is given with argument `-p=/some/path` instead of `-p /some/path`
2. argument `-export-fixes /tmp/tmppri1nz_t/tmpeko_clr7.yaml` uses an autogenerated random file that changes for each run.

I could workaround these issues with the following patch:
```diff
diff --git a/clang-tidy-cache b/clang-tidy-cache
index 279aacd..8172107 100755
--- a/clang-tidy-cache
+++ b/clang-tidy-cache
@@ -29,6 +29,14 @@ class ClangTidyCacheOpts(object):

         self._strip_list = os.getenv("CTCACHE_STRIP", "").split(':')

+        tmpArgs = []
+        for arg in args:
+            if arg.startswith("-p="):
+                tmpArgs.append("-p")
+                tmpArgs.append(arg[3:])
+            else:
+                tmpArgs.append(arg)
+        args = tmpArgs
         if args.count("--") == 1:
             # Invoked with compiler args on the actual command line
             i = args.index("--")
@@ -483,7 +491,15 @@ def hash_inputs(opts):

     for chunk in sorted(set([opts.adjust_chunk(arg) for arg in co_args[1:]])):
         result.update(chunk)
-    for chunk in sorted(set([opts.adjust_chunk(arg) for arg in ct_args[1:]])):
+    tmpArgs = []
+    i = 1
+    while i < len(ct_args):
+      if ct_args[i] == "-export-fixes":
+          i += 2 # ignore args '-export-fixes /path/to/file.yaml'
+          continue
+      tmpArgs.append(ct_args[i])
+      i += 1
+    for chunk in sorted(set([opts.adjust_chunk(arg) for arg in tmpArgs])):
         result.update(chunk)

     return result.hexdigest()
```

**Comment by matus-chochlik** [comment]
Hi, pushed some changes. Could you please check if that helped?

**Comment by jeremy-coulon** [comment]
No.

Debugging your change:
```python
        # splits arguments starting with - on the first =
        print("before: {}".format(args))
        args = [arg.split('=', 1) if arg.startswith('-') else arg for arg in args]
        args = [arg for sub in args for arg in sub]
        print("after: {}".format(args))
```

gives me:
```
before: ['/usr/bin/clang-tidy', '-export-fixes', '/tmp/tmpi6qgjwl6/tmpzfll9636.yaml', '-p=/some/path', '/path/to/file.cpp']
after: ['/', 'u', 's', 'r', '/', 'b', 'i', 'n', '/', 'c', 'l', 'a', 'n', 'g', '-', 't', 'i', 'd', 'y', '-export-fixes', '/', 't', 'm', 'p', '/', 't', 'm', 'p', 'i', '6', 'q', 'g', 'j', 'w', 'l', '6', '/', 't', 'm', 'p', 'z', 'f', 'l', 'l', '9', '6', '3', '6', '.', 'y', 'a', 'm', 'l', '-p', '/some/path', '/', 'p', 'a', 't', 'h', '/', 't', 'o', '/', 'f', 'i', 'l', 'e', '.', 'c', 'p', 'p']
```

**Comment by matus-chochlik** [comment]
right, pushed a new one

**Comment by matus-chochlik** [comment]
did the new changes help?

**Comment by jeremy-coulon** [comment]
I will try on monday.

Le sam. 21 janv. 2023, 18:40, Matus Chochlik ***@***.***> a
écrit :

**Comment by jeremy-coulon** [comment]
Yes it works.

**Comment by matus-chochlik** [comment]
okay thanks, closing this issue. Feel free to reopen or open a new one if additional changes are necessary.
