### ISSUE TITLE
Consider readonly option for public S3 buckets

### ISSUE THREAD

**Issue by Felixoid** [matus-chochlik/ctcache#17]
Hello. The `mozilla/sccache` supports read-only access to the cache when [SCCACHE_S3_NO_CREDENTIALS](https://github.com/mozilla/sccache/blob/main/docs/S3.md#credentials) ENV is set.

Do you think it's possible/easy to implement it in ctcache too?

**Comment by matus-chochlik** [comment]
You mean that the client would only read exisitng entries, but not make new ones in that mode? If so that should be doable.

**Comment by Felixoid** [comment]
I am playing with it in https://github.com/matus-chochlik/ctcache/compare/main...Felixoid:ctcache:readonly-s3?expand=1, plan to test it soon

**Comment by matus-chochlik** [comment]
When you have a working MR I'd be happy to merge it.

**Comment by Felixoid** [comment]
Solved by #18
