### ISSUE TITLE
Question: Shared cache

### ISSUE THREAD

**Issue by andrewkcorcoran** [matus-chochlik/ctcache#28]
Does ctcache support sharing 'local' cache locations across multiple machines? Say for example running builds on multiple servers but having a shared network attached storage with a single ctcache shared by all the servers? The servers could be running builds concurrently with each other so could be reading and writing to the cache at the same time.

**Comment by matus-chochlik** [comment]
Hi. ctcache was originally developed and used (at a project with ~20-30 devs) with this use case in mind. But in the last couple of years there were multiple 3rd party changes made and I haven't tested if this still works properly.

There is this [https://github.com/matus-chochlik/ctcache/blob/main/doc/overview.pdf] presentation that discusses this briefly on slides 55-58. 

Basically the CTCACHE_STRIP variable needs to set properly by the clients. If you have an environment where you could test it it would be useful to have feedback if this still works.

**Comment by andrewkcorcoran** [comment]
Cool I'll give it a go. The presentation only mentions sharing a cache using the cache server hence why I wanted to clarify if a locally mounted network storage approach would in theory work also.
