### ISSUE TITLE
Failing to parse the compile commands DB

### ISSUE THREAD

**Issue by ZeronSix** [matus-chochlik/ctcache#29]
Hello!

Thanks for a fantastic tool! However, I tried to integrate ctcache into my project and experienced the following issue. `_load_compile_command_db` fails silently when trying to parse the JSON. The problem seems so be that the backslashes are not escaped properly: `Expecting ',' delimiter: line 1094 column 151 (char 232775)`. The `compile_commands.json` file causing the error is attached. 

Getting rid of `replace` in `_load_compile_command_db` seems to work as a temporary workaround for me:
```python
def _load_compile_command_db(self, filename):
    try:
        f = open(filename)
        self._compile_commands_db = json.loads(f.read())
        f.close()
    except Exception:
        return False
```

Also, I think that it would probably be better to explicitly signal about JSON parsing errors instead of silently suppressing them.

[compile_commands.json.txt](https://github.com/matus-chochlik/ctcache/files/12728243/compile_commands.json.txt)

**Comment by matus-chochlik** [comment]
Hi, thanks for the report! I've pushed some small changes to main. Please test and let me know if it helps.

**Comment by ZeronSix** [comment]
Unfortunately, now it fails with `[build] Loading compile command DB failed: NameError("name 'j' is not defined")`

[compile_commands.json.txt](https://github.com/matus-chochlik/ctcache/files/12736991/compile_commands.json.txt)

**Comment by matus-chochlik** [comment]
Ugh, bad copy-pasta, should be fixed now

**Comment by ZeronSix** [comment]
Now it works, thanks!
