### ISSUE TITLE
Client/server mode no longer working by default

### ISSUE THREAD

**Issue by tonygould** [matus-chochlik/ctcache#30]
Following doesn't work any more

> This mode is enabled by setting the CTCACHE_HOST (localhost by default) and optionally CTCACHE_PORT (5000 by default) environment variables.

This is after commit a10ce62b6d237bcdd531f08a8fa9401a28640573. Simplest fix is to change the new option 

```
    def save_output(self) -> bool:
        return os.getenv("CTCACHE_SAVE_OUTPUT", "1") == "1"
```

so that it returns `false` by default, maintaining the old behaviour by default, i.e. `return os.getenv("CTCACHE_SAVE_OUTPUT", "0") == "1"`.

**Comment by matus-chochlik** [comment]
Hi, I've pushed the suggested change to main. Thanks for the bug report
