### ISSUE TITLE
Some issues with MSVC

### ISSUE THREAD

**Issue by solarispika** [matus-chochlik/ctcache#35]
I have a project built using CMake with Ninja build system and it supports Windows so the compiler is `cl.exe` from MSVC.

I tried to use `ctcache` and had some issues that I think can be fixed easily:

1. `cl.exe` writes file name to standard error even when successfully pre-compiled the file, causing `ctcache` to fail to cache here
    https://github.com/matus-chochlik/ctcache/blob/dac994ee5b982ead85bdf805a2e84c517ed45caf/clang-tidy-cache#L858-L859
    I think the check can be changed to look at `proc.returncode`.
2. In adjusting compiler options to print precompiled content here
    https://github.com/matus-chochlik/ctcache/blob/dac994ee5b982ead85bdf805a2e84c517ed45caf/clang-tidy-cache#L102-L104
    The [`-P`](https://learn.microsoft.com/en-us/cpp/build/reference/p-preprocess-to-a-file?view=msvc-170) option tells `cl.exe` to write the content to a `.i` file. To achieve what is desired by the code, it should change [`-E`](https://learn.microsoft.com/en-us/cpp/build/reference/e-preprocess-to-stdout?view=msvc-170) to [`-EP`](https://learn.microsoft.com/en-us/cpp/build/reference/ep-preprocess-to-stdout-without-hash-line-directives?view=msvc-170).
3. In `FileLock.release`, before `os.unlink`, `self.lockfile` should be closed first, or `os.unlink` will fail.
    https://github.com/matus-chochlik/ctcache/blob/dac994ee5b982ead85bdf805a2e84c517ed45caf/clang-tidy-cache#L450-L457

With these changes, I can successfully cache `clang-tidy`'s output.

I am just not sure how would you like to fix this in a proper way.

**Comment by matus-chochlik** [comment]
Hi, thank you for the report. If you have a PR ready and it doesn't break anything with other compilers, I'd be happy to merge it.

**Comment by matus-chochlik** [comment]
I've added and pushed code to close the lock file before unlinking, the other changes will require more testing.

**Comment by matus-chochlik** [comment]
Neither g++ nor clang recognize the -EP option, so there has to be another solution to the issue with the -P argument.

**Comment by matus-chochlik** [comment]
your PR is in draft state, which prevents it from being merged, is it intentional?

**Comment by solarispika** [comment]
Oh, I wanted to see if you have any suggestion on it, and I was not sure if this test of compiler is robust or not, so I just made it a draft.
I am using it with both apple clang and msvc without any issue, I can remove the draft now.

**Comment by matus-chochlik** [comment]
Thanks for the PR. Merged and done some refactoring. Please check and let me know if everything works.

**Comment by solarispika** [comment]
https://github.com/matus-chochlik/ctcache/blob/ad3af7ae8b18082a9b05edb2fbc1b90fb3b7b703/clang-tidy-cache#L962

`options` should be `opts`.

**Comment by matus-chochlik** [comment]
good catch I only tested it with running clang-tidy-cache manually
