### ISSUE TITLE
[suggestion] change CTCACHE_STRIP delimiter to platform default path delimiter

### ISSUE THREAD

**Issue by lhocmf** [matus-chochlik/ctcache#40]
Using `CTCACHE_STRIP` gets a bit hairy under Windows, as the currently used delimiter (`:`) is part of each and every absolute path. This unnecessarily makes usage of `CTCACHE_STRIP` harder for absolute paths.

This is the relevant piece of code:

https://github.com/matus-chochlik/ctcache/blob/b6ef9597fc8ecef26861899a53280eb91a1a5b41/clang-tidy-cache#L61

It would be nice if this could be changed to use `os.pathsep` instead of `:` in order to adhere to different OS conventions, unless there is a specific reason to prefer `:` as the delimiter.

**Comment by matus-chochlik** [comment]
Done. Thanks for the suggestion.
