### ISSUE TITLE
<class 'NameError'>: NameError("name 'msg' is not defined")

### ISSUE THREAD

**Issue by andrewkcorcoran** [matus-chochlik/ctcache#43]
https://github.com/matus-chochlik/ctcache/commit/a08fd566cb81088d1d78fc5b4b6c1f63930bb4df#diff-64d773e164aa5d2b3b02f31d4a9dabc53edbd4add4da2c341c7f62760056eaf7L446 this commit removes the creation of `msg` but the `raise` call still refers to `msg` resulting in the above error.

**Comment by matus-chochlik** [comment]
Fixed and pushed.
