### ISSUE TITLE
Successful compile command reported as erroneous

### ISSUE THREAD

**Issue by Masrepus** [matus-chochlik/ctcache#61]
I was wondering why ctcache didn't cache any clang-tidy output for my header files and after some investigation it turned out that the compile command stored for my header files would emit `warning: treating 'c-header' input as 'c++-header' when in C++ mode, this behavior is deprecated [-Wdeprecated]` when executed, but still succeed. Your current logic for any compiler that isn't MSVC is that you don't look at the compile command exit code but rather whether stderr is empty (https://github.com/matus-chochlik/ctcache/blob/debfea68152c5221d8f409cbef85dc5d0f98071d/clang-tidy-cache#L1183).

Shouldn't a check for the exit code suffice for all compilers?

**Comment by matus-chochlik** [comment]
Hi, IIRC there were some examples where the return code was zero on Linux, but there were still some (arguably) errors printed to stderr. The decision was made to not cache the result with false positives, rather than to let false negative clang-tidy result to pass.

**Comment by Masrepus** [comment]
I see, makes sense. Thanks for clarifying!
